### PR TITLE
clangformat

### PR DESCRIPTION
**Pull request by il-steffen**
Rebased to apply on top of new 'wip-logging' PR

### CODE REVIEW

**Comment by XVilka** [comment]
Speaking about https://github.com/nyx-fuzz/QEMU-Nyx/pull/31/commits/27460a5fc02647878c17fbaa5fc44a1619a17f7b
These changes would prevent from updating to the newer QEMU: https://github.com/nyx-fuzz/QEMU-Nyx/issues/32
I recommend to restrict clang-format application only to Nyx-specific files and leave QEMU files unchanged. They discuss possibility to use clang-format some time in the future anyway: https://lore.kernel.org/qemu-devel/YxHEOEpjABDZu18j@redhat.com/t/#m768ba2cefb0852b97d84dde9d4f36752910048c6

**Comment by il-steffen** [comment]
> Speaking about [27460a5](https://github.com/nyx-fuzz/QEMU-Nyx/commit/27460a5fc02647878c17fbaa5fc44a1619a17f7b)

The patch only reformats the code added by Nyx.

**Comment by XVilka** [comment]
@il-steffen ignore my comment then.

**Comment by il-steffen** [comment]
closing for rebased #33   (original clangformat branch still in my repo)

**Pull request closed without merging**
