### PR TITLE
logging

### PR DESCRIPTION
**Pull request by il-steffen**
something to cherry-pick:
- "verbose" option based on previous commit (renamed to debug, and debug renamed to asan)
- printf fixes

wip / for feedback:
- replace all printf with logging macro
- implement logging macros with qemu logging facility

### CODE REVIEW

**Comment by il-steffen** [comment]
revised version:
- introduce generic wrappers in debug.h to cover stderr/stdout/logging cases.
- qemu_log_mask() is silent by default but can be activated with -d and redirected together with qemu_log() outputs using -D
- several hardcoded printf() still remain in the code gated by debug macros. could replace with nyx_debug_p(PREFIX, ...)

**Comment by il-steffen** [comment]
let me know if this is okay...the clang-format patches apply on top..

**Comment by il-steffen** [comment]
Switched from --enable-gtk to --disable-gtk.

**Comment by schumilo** [comment]
Thanks!

**Pull request merged**
